print('When was your year of birth:')
born=int(input())
print('What is the year right now?')
year=int(input())
print('Age in Years:',year-born)
print('Age in Months:',(year-born)*12)
print('Age in Weeks:',(year-born)*12*4)
print('Age in Days:',(year-born)*365)
print('Age in Hours:',(year-born)*365*24)
print('Age in Minutes:',(year-born)*365*24*60)
print('Age in Seconds:',(year-born)*365*24*60*60)
print('Age in Mili-Seconds:',(year-born)*365*24*60*60*60)
