print('What is your name?')
name=input()
print('What is your age?')
age=input()
print('What is your state?')
state=input()
print(name,age,state.endswith('yan'))
print(name,age,state.isalpha())
print(name,age,state.isnumeric())
print(name,age,state.isupper())
print(name,age,state.islower())
