months='JanFebMarAprMayJunJulAugSepOctNovDec'
January=months[0:3]
print(January)
Febrauary=months[3:6]
print(Febrauary)
March=months[6:9]
print(March)
April=months[9:12]
print(April)
May=months[12:15]
print(May)
June=months[15:18]
print(June)
July=months[18:21]
print(July)
August=months[21:24]
print(August)
September=months[24:27]
print(September)
October=months[27:30]
print(October)
November=months[30:33]
print(November)
December=months[33:36]
print(December)
